# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_omni.proto_gen.omni.resources import resources_pb2 as omni_dot_resources_dot_resources__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in omni/resources/resources_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResourceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/omni.resources.ResourceService/Get',
                request_serializer=omni_dot_resources_dot_resources__pb2.GetRequest.SerializeToString,
                response_deserializer=omni_dot_resources_dot_resources__pb2.GetResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/omni.resources.ResourceService/List',
                request_serializer=omni_dot_resources_dot_resources__pb2.ListRequest.SerializeToString,
                response_deserializer=omni_dot_resources_dot_resources__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/omni.resources.ResourceService/Create',
                request_serializer=omni_dot_resources_dot_resources__pb2.CreateRequest.SerializeToString,
                response_deserializer=omni_dot_resources_dot_resources__pb2.CreateResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/omni.resources.ResourceService/Update',
                request_serializer=omni_dot_resources_dot_resources__pb2.UpdateRequest.SerializeToString,
                response_deserializer=omni_dot_resources_dot_resources__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/omni.resources.ResourceService/Delete',
                request_serializer=omni_dot_resources_dot_resources__pb2.DeleteRequest.SerializeToString,
                response_deserializer=omni_dot_resources_dot_resources__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Teardown = channel.unary_unary(
                '/omni.resources.ResourceService/Teardown',
                request_serializer=omni_dot_resources_dot_resources__pb2.DeleteRequest.SerializeToString,
                response_deserializer=omni_dot_resources_dot_resources__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/omni.resources.ResourceService/Watch',
                request_serializer=omni_dot_resources_dot_resources__pb2.WatchRequest.SerializeToString,
                response_deserializer=omni_dot_resources_dot_resources__pb2.WatchResponse.FromString,
                _registered_method=True)
        self.Controllers = channel.unary_unary(
                '/omni.resources.ResourceService/Controllers',
                request_serializer=omni_dot_resources_dot_resources__pb2.ControllersRequest.SerializeToString,
                response_deserializer=omni_dot_resources_dot_resources__pb2.ControllersResponse.FromString,
                _registered_method=True)
        self.DependencyGraph = channel.unary_unary(
                '/omni.resources.ResourceService/DependencyGraph',
                request_serializer=omni_dot_resources_dot_resources__pb2.DependencyGraphRequest.SerializeToString,
                response_deserializer=omni_dot_resources_dot_resources__pb2.DependencyGraphResponse.FromString,
                _registered_method=True)


class ResourceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Teardown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Controllers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DependencyGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResourceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=omni_dot_resources_dot_resources__pb2.GetRequest.FromString,
                    response_serializer=omni_dot_resources_dot_resources__pb2.GetResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=omni_dot_resources_dot_resources__pb2.ListRequest.FromString,
                    response_serializer=omni_dot_resources_dot_resources__pb2.ListResponse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=omni_dot_resources_dot_resources__pb2.CreateRequest.FromString,
                    response_serializer=omni_dot_resources_dot_resources__pb2.CreateResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=omni_dot_resources_dot_resources__pb2.UpdateRequest.FromString,
                    response_serializer=omni_dot_resources_dot_resources__pb2.UpdateResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=omni_dot_resources_dot_resources__pb2.DeleteRequest.FromString,
                    response_serializer=omni_dot_resources_dot_resources__pb2.DeleteResponse.SerializeToString,
            ),
            'Teardown': grpc.unary_unary_rpc_method_handler(
                    servicer.Teardown,
                    request_deserializer=omni_dot_resources_dot_resources__pb2.DeleteRequest.FromString,
                    response_serializer=omni_dot_resources_dot_resources__pb2.DeleteResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=omni_dot_resources_dot_resources__pb2.WatchRequest.FromString,
                    response_serializer=omni_dot_resources_dot_resources__pb2.WatchResponse.SerializeToString,
            ),
            'Controllers': grpc.unary_unary_rpc_method_handler(
                    servicer.Controllers,
                    request_deserializer=omni_dot_resources_dot_resources__pb2.ControllersRequest.FromString,
                    response_serializer=omni_dot_resources_dot_resources__pb2.ControllersResponse.SerializeToString,
            ),
            'DependencyGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.DependencyGraph,
                    request_deserializer=omni_dot_resources_dot_resources__pb2.DependencyGraphRequest.FromString,
                    response_serializer=omni_dot_resources_dot_resources__pb2.DependencyGraphResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omni.resources.ResourceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('omni.resources.ResourceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResourceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omni.resources.ResourceService/Get',
            omni_dot_resources_dot_resources__pb2.GetRequest.SerializeToString,
            omni_dot_resources_dot_resources__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omni.resources.ResourceService/List',
            omni_dot_resources_dot_resources__pb2.ListRequest.SerializeToString,
            omni_dot_resources_dot_resources__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omni.resources.ResourceService/Create',
            omni_dot_resources_dot_resources__pb2.CreateRequest.SerializeToString,
            omni_dot_resources_dot_resources__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omni.resources.ResourceService/Update',
            omni_dot_resources_dot_resources__pb2.UpdateRequest.SerializeToString,
            omni_dot_resources_dot_resources__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omni.resources.ResourceService/Delete',
            omni_dot_resources_dot_resources__pb2.DeleteRequest.SerializeToString,
            omni_dot_resources_dot_resources__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Teardown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omni.resources.ResourceService/Teardown',
            omni_dot_resources_dot_resources__pb2.DeleteRequest.SerializeToString,
            omni_dot_resources_dot_resources__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/omni.resources.ResourceService/Watch',
            omni_dot_resources_dot_resources__pb2.WatchRequest.SerializeToString,
            omni_dot_resources_dot_resources__pb2.WatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Controllers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omni.resources.ResourceService/Controllers',
            omni_dot_resources_dot_resources__pb2.ControllersRequest.SerializeToString,
            omni_dot_resources_dot_resources__pb2.ControllersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DependencyGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/omni.resources.ResourceService/DependencyGraph',
            omni_dot_resources_dot_resources__pb2.DependencyGraphRequest.SerializeToString,
            omni_dot_resources_dot_resources__pb2.DependencyGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
