# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1alpha1/resource.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'v1alpha1/resource.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17v1alpha1/resource.proto\x12\rcosi.resource\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x03\n\x08Metadata\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\r\n\x05owner\x18\x05 \x01(\t\x12\r\n\x05phase\x18\x06 \x01(\t\x12+\n\x07\x63reated\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nfinalizers\x18\t \x03(\t\x12=\n\x0b\x61nnotations\x18\x0b \x03(\x0b\x32(.cosi.resource.Metadata.AnnotationsEntry\x12\x33\n\x06labels\x18\n \x03(\x0b\x32#.cosi.resource.Metadata.LabelsEntry\x1a\x32\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"-\n\x04Spec\x12\x12\n\nproto_spec\x18\x01 \x01(\x0c\x12\x11\n\tyaml_spec\x18\x02 \x01(\t\"X\n\x08Resource\x12)\n\x08metadata\x18\x01 \x01(\x0b\x32\x17.cosi.resource.Metadata\x12!\n\x04spec\x18\x02 \x01(\x0b\x32\x13.cosi.resource.Spec\"\xd9\x01\n\tLabelTerm\x12\x0b\n\x03key\x18\x01 \x01(\t\x12.\n\x02op\x18\x02 \x01(\x0e\x32\".cosi.resource.LabelTerm.Operation\x12\r\n\x05value\x18\x03 \x03(\t\x12\x0e\n\x06invert\x18\x05 \x01(\x08\"p\n\tOperation\x12\n\n\x06\x45XISTS\x10\x00\x12\t\n\x05\x45QUAL\x10\x01\x12\x12\n\nNOT_EXISTS\x10\x02\x1a\x02\x08\x01\x12\x06\n\x02IN\x10\x03\x12\x06\n\x02LT\x10\x04\x12\x07\n\x03LTE\x10\x05\x12\x0e\n\nLT_NUMERIC\x10\x06\x12\x0f\n\x0bLTE_NUMERIC\x10\x07\"5\n\nLabelQuery\x12\'\n\x05terms\x18\x01 \x03(\x0b\x32\x18.cosi.resource.LabelTerm\"\x19\n\x07IDQuery\x12\x0e\n\x06regexp\x18\x01 \x01(\tB.Z,github.com/cosi-project/runtime/api/v1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1alpha1.resource_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/cosi-project/runtime/api/v1alpha1'
  _globals['_METADATA_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_METADATA_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_METADATA_LABELSENTRY']._loaded_options = None
  _globals['_METADATA_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_LABELTERM_OPERATION'].values_by_name["NOT_EXISTS"]._loaded_options = None
  _globals['_LABELTERM_OPERATION'].values_by_name["NOT_EXISTS"]._serialized_options = b'\010\001'
  _globals['_METADATA']._serialized_start=76
  _globals['_METADATA']._serialized_end=503
  _globals['_METADATA_ANNOTATIONSENTRY']._serialized_start=406
  _globals['_METADATA_ANNOTATIONSENTRY']._serialized_end=456
  _globals['_METADATA_LABELSENTRY']._serialized_start=458
  _globals['_METADATA_LABELSENTRY']._serialized_end=503
  _globals['_SPEC']._serialized_start=505
  _globals['_SPEC']._serialized_end=550
  _globals['_RESOURCE']._serialized_start=552
  _globals['_RESOURCE']._serialized_end=640
  _globals['_LABELTERM']._serialized_start=643
  _globals['_LABELTERM']._serialized_end=860
  _globals['_LABELTERM_OPERATION']._serialized_start=748
  _globals['_LABELTERM_OPERATION']._serialized_end=860
  _globals['_LABELQUERY']._serialized_start=862
  _globals['_LABELQUERY']._serialized_end=915
  _globals['_IDQUERY']._serialized_start=917
  _globals['_IDQUERY']._serialized_end=942
# @@protoc_insertion_point(module_scope)
