# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/omni.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/omni.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ommon/omni.proto\x12\x06\x63ommon\"#\n\x07\x43ontext\x12\x0c\n\x04name\x18\x01 \x01(\tJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04*.\n\x07Runtime\x12\x0e\n\nKubernetes\x10\x00\x12\t\n\x05Talos\x10\x01\x12\x08\n\x04Omni\x10\x02\x42.Z,github.com/siderolabs/omni/client/api/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.omni_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/siderolabs/omni/client/api/common'
  _globals['_RUNTIME']._serialized_start=66
  _globals['_RUNTIME']._serialized_end=112
  _globals['_CONTEXT']._serialized_start=29
  _globals['_CONTEXT']._serialized_end=64
# @@protoc_insertion_point(module_scope)
