# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcp_omni.proto_gen.common import common_pb2 as common_dot_common__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from mcp_omni.proto_gen.omni.management import management_pb2 as omni_dot_management_dot_management__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in omni/management/management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Kubeconfig = channel.unary_unary(
                '/management.ManagementService/Kubeconfig',
                request_serializer=omni_dot_management_dot_management__pb2.KubeconfigRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.KubeconfigResponse.FromString,
                _registered_method=True)
        self.Talosconfig = channel.unary_unary(
                '/management.ManagementService/Talosconfig',
                request_serializer=omni_dot_management_dot_management__pb2.TalosconfigRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.TalosconfigResponse.FromString,
                _registered_method=True)
        self.Omniconfig = channel.unary_unary(
                '/management.ManagementService/Omniconfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.OmniconfigResponse.FromString,
                _registered_method=True)
        self.MachineLogs = channel.unary_stream(
                '/management.ManagementService/MachineLogs',
                request_serializer=omni_dot_management_dot_management__pb2.MachineLogsRequest.SerializeToString,
                response_deserializer=common_dot_common__pb2.Data.FromString,
                _registered_method=True)
        self.ValidateConfig = channel.unary_unary(
                '/management.ManagementService/ValidateConfig',
                request_serializer=omni_dot_management_dot_management__pb2.ValidateConfigRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ValidateJSONSchema = channel.unary_unary(
                '/management.ManagementService/ValidateJSONSchema',
                request_serializer=omni_dot_management_dot_management__pb2.ValidateJsonSchemaRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.ValidateJsonSchemaResponse.FromString,
                _registered_method=True)
        self.CreateServiceAccount = channel.unary_unary(
                '/management.ManagementService/CreateServiceAccount',
                request_serializer=omni_dot_management_dot_management__pb2.CreateServiceAccountRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.CreateServiceAccountResponse.FromString,
                _registered_method=True)
        self.RenewServiceAccount = channel.unary_unary(
                '/management.ManagementService/RenewServiceAccount',
                request_serializer=omni_dot_management_dot_management__pb2.RenewServiceAccountRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.RenewServiceAccountResponse.FromString,
                _registered_method=True)
        self.ListServiceAccounts = channel.unary_unary(
                '/management.ManagementService/ListServiceAccounts',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.ListServiceAccountsResponse.FromString,
                _registered_method=True)
        self.DestroyServiceAccount = channel.unary_unary(
                '/management.ManagementService/DestroyServiceAccount',
                request_serializer=omni_dot_management_dot_management__pb2.DestroyServiceAccountRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.KubernetesUpgradePreChecks = channel.unary_unary(
                '/management.ManagementService/KubernetesUpgradePreChecks',
                request_serializer=omni_dot_management_dot_management__pb2.KubernetesUpgradePreChecksRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.KubernetesUpgradePreChecksResponse.FromString,
                _registered_method=True)
        self.KubernetesSyncManifests = channel.unary_stream(
                '/management.ManagementService/KubernetesSyncManifests',
                request_serializer=omni_dot_management_dot_management__pb2.KubernetesSyncManifestRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.KubernetesSyncManifestResponse.FromString,
                _registered_method=True)
        self.CreateSchematic = channel.unary_unary(
                '/management.ManagementService/CreateSchematic',
                request_serializer=omni_dot_management_dot_management__pb2.CreateSchematicRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.CreateSchematicResponse.FromString,
                _registered_method=True)
        self.CreateSchematicFromRaw = channel.unary_unary(
                '/management.ManagementService/CreateSchematicFromRaw',
                request_serializer=omni_dot_management_dot_management__pb2.CreateSchematicFromRawRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.CreateSchematicResponse.FromString,
                _registered_method=True)
        self.GetSupportBundle = channel.unary_stream(
                '/management.ManagementService/GetSupportBundle',
                request_serializer=omni_dot_management_dot_management__pb2.GetSupportBundleRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.GetSupportBundleResponse.FromString,
                _registered_method=True)
        self.ReadAuditLog = channel.unary_stream(
                '/management.ManagementService/ReadAuditLog',
                request_serializer=omni_dot_management_dot_management__pb2.ReadAuditLogRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.ReadAuditLogResponse.FromString,
                _registered_method=True)
        self.MaintenanceUpgrade = channel.unary_unary(
                '/management.ManagementService/MaintenanceUpgrade',
                request_serializer=omni_dot_management_dot_management__pb2.MaintenanceUpgradeRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.MaintenanceUpgradeResponse.FromString,
                _registered_method=True)
        self.GetMachineJoinConfig = channel.unary_unary(
                '/management.ManagementService/GetMachineJoinConfig',
                request_serializer=omni_dot_management_dot_management__pb2.GetMachineJoinConfigRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.GetMachineJoinConfigResponse.FromString,
                _registered_method=True)
        self.CreateJoinToken = channel.unary_unary(
                '/management.ManagementService/CreateJoinToken',
                request_serializer=omni_dot_management_dot_management__pb2.CreateJoinTokenRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.CreateJoinTokenResponse.FromString,
                _registered_method=True)
        self.ResetNodeUniqueToken = channel.unary_unary(
                '/management.ManagementService/ResetNodeUniqueToken',
                request_serializer=omni_dot_management_dot_management__pb2.ResetNodeUniqueTokenRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.ResetNodeUniqueTokenResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/management.ManagementService/CreateUser',
                request_serializer=omni_dot_management_dot_management__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/management.ManagementService/ListUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/management.ManagementService/UpdateUser',
                request_serializer=omni_dot_management_dot_management__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DestroyUser = channel.unary_unary(
                '/management.ManagementService/DestroyUser',
                request_serializer=omni_dot_management_dot_management__pb2.DestroyUserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.MachinePowerOff = channel.unary_unary(
                '/management.ManagementService/MachinePowerOff',
                request_serializer=omni_dot_management_dot_management__pb2.MachinePowerOffRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.MachinePowerOffResponse.FromString,
                _registered_method=True)
        self.MachinePowerOn = channel.unary_unary(
                '/management.ManagementService/MachinePowerOn',
                request_serializer=omni_dot_management_dot_management__pb2.MachinePowerOnRequest.SerializeToString,
                response_deserializer=omni_dot_management_dot_management__pb2.MachinePowerOnResponse.FromString,
                _registered_method=True)


class ManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Kubeconfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Talosconfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Omniconfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MachineLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateJSONSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateServiceAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewServiceAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServiceAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyServiceAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KubernetesUpgradePreChecks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KubernetesSyncManifests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSchematic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSchematicFromRaw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportBundle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAuditLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaintenanceUpgrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMachineJoinConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateJoinToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetNodeUniqueToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MachinePowerOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MachinePowerOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Kubeconfig': grpc.unary_unary_rpc_method_handler(
                    servicer.Kubeconfig,
                    request_deserializer=omni_dot_management_dot_management__pb2.KubeconfigRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.KubeconfigResponse.SerializeToString,
            ),
            'Talosconfig': grpc.unary_unary_rpc_method_handler(
                    servicer.Talosconfig,
                    request_deserializer=omni_dot_management_dot_management__pb2.TalosconfigRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.TalosconfigResponse.SerializeToString,
            ),
            'Omniconfig': grpc.unary_unary_rpc_method_handler(
                    servicer.Omniconfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.OmniconfigResponse.SerializeToString,
            ),
            'MachineLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.MachineLogs,
                    request_deserializer=omni_dot_management_dot_management__pb2.MachineLogsRequest.FromString,
                    response_serializer=common_dot_common__pb2.Data.SerializeToString,
            ),
            'ValidateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateConfig,
                    request_deserializer=omni_dot_management_dot_management__pb2.ValidateConfigRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ValidateJSONSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateJSONSchema,
                    request_deserializer=omni_dot_management_dot_management__pb2.ValidateJsonSchemaRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.ValidateJsonSchemaResponse.SerializeToString,
            ),
            'CreateServiceAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateServiceAccount,
                    request_deserializer=omni_dot_management_dot_management__pb2.CreateServiceAccountRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.CreateServiceAccountResponse.SerializeToString,
            ),
            'RenewServiceAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewServiceAccount,
                    request_deserializer=omni_dot_management_dot_management__pb2.RenewServiceAccountRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.RenewServiceAccountResponse.SerializeToString,
            ),
            'ListServiceAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServiceAccounts,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.ListServiceAccountsResponse.SerializeToString,
            ),
            'DestroyServiceAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyServiceAccount,
                    request_deserializer=omni_dot_management_dot_management__pb2.DestroyServiceAccountRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'KubernetesUpgradePreChecks': grpc.unary_unary_rpc_method_handler(
                    servicer.KubernetesUpgradePreChecks,
                    request_deserializer=omni_dot_management_dot_management__pb2.KubernetesUpgradePreChecksRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.KubernetesUpgradePreChecksResponse.SerializeToString,
            ),
            'KubernetesSyncManifests': grpc.unary_stream_rpc_method_handler(
                    servicer.KubernetesSyncManifests,
                    request_deserializer=omni_dot_management_dot_management__pb2.KubernetesSyncManifestRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.KubernetesSyncManifestResponse.SerializeToString,
            ),
            'CreateSchematic': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchematic,
                    request_deserializer=omni_dot_management_dot_management__pb2.CreateSchematicRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.CreateSchematicResponse.SerializeToString,
            ),
            'CreateSchematicFromRaw': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchematicFromRaw,
                    request_deserializer=omni_dot_management_dot_management__pb2.CreateSchematicFromRawRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.CreateSchematicResponse.SerializeToString,
            ),
            'GetSupportBundle': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSupportBundle,
                    request_deserializer=omni_dot_management_dot_management__pb2.GetSupportBundleRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.GetSupportBundleResponse.SerializeToString,
            ),
            'ReadAuditLog': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadAuditLog,
                    request_deserializer=omni_dot_management_dot_management__pb2.ReadAuditLogRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.ReadAuditLogResponse.SerializeToString,
            ),
            'MaintenanceUpgrade': grpc.unary_unary_rpc_method_handler(
                    servicer.MaintenanceUpgrade,
                    request_deserializer=omni_dot_management_dot_management__pb2.MaintenanceUpgradeRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.MaintenanceUpgradeResponse.SerializeToString,
            ),
            'GetMachineJoinConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMachineJoinConfig,
                    request_deserializer=omni_dot_management_dot_management__pb2.GetMachineJoinConfigRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.GetMachineJoinConfigResponse.SerializeToString,
            ),
            'CreateJoinToken': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJoinToken,
                    request_deserializer=omni_dot_management_dot_management__pb2.CreateJoinTokenRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.CreateJoinTokenResponse.SerializeToString,
            ),
            'ResetNodeUniqueToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetNodeUniqueToken,
                    request_deserializer=omni_dot_management_dot_management__pb2.ResetNodeUniqueTokenRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.ResetNodeUniqueTokenResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=omni_dot_management_dot_management__pb2.CreateUserRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.CreateUserResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.ListUsersResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=omni_dot_management_dot_management__pb2.UpdateUserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DestroyUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyUser,
                    request_deserializer=omni_dot_management_dot_management__pb2.DestroyUserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'MachinePowerOff': grpc.unary_unary_rpc_method_handler(
                    servicer.MachinePowerOff,
                    request_deserializer=omni_dot_management_dot_management__pb2.MachinePowerOffRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.MachinePowerOffResponse.SerializeToString,
            ),
            'MachinePowerOn': grpc.unary_unary_rpc_method_handler(
                    servicer.MachinePowerOn,
                    request_deserializer=omni_dot_management_dot_management__pb2.MachinePowerOnRequest.FromString,
                    response_serializer=omni_dot_management_dot_management__pb2.MachinePowerOnResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'management.ManagementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('management.ManagementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Kubeconfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/Kubeconfig',
            omni_dot_management_dot_management__pb2.KubeconfigRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.KubeconfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Talosconfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/Talosconfig',
            omni_dot_management_dot_management__pb2.TalosconfigRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.TalosconfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Omniconfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/Omniconfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            omni_dot_management_dot_management__pb2.OmniconfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MachineLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/management.ManagementService/MachineLogs',
            omni_dot_management_dot_management__pb2.MachineLogsRequest.SerializeToString,
            common_dot_common__pb2.Data.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/ValidateConfig',
            omni_dot_management_dot_management__pb2.ValidateConfigRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateJSONSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/ValidateJSONSchema',
            omni_dot_management_dot_management__pb2.ValidateJsonSchemaRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.ValidateJsonSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateServiceAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/CreateServiceAccount',
            omni_dot_management_dot_management__pb2.CreateServiceAccountRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.CreateServiceAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewServiceAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/RenewServiceAccount',
            omni_dot_management_dot_management__pb2.RenewServiceAccountRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.RenewServiceAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServiceAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/ListServiceAccounts',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            omni_dot_management_dot_management__pb2.ListServiceAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyServiceAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/DestroyServiceAccount',
            omni_dot_management_dot_management__pb2.DestroyServiceAccountRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KubernetesUpgradePreChecks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/KubernetesUpgradePreChecks',
            omni_dot_management_dot_management__pb2.KubernetesUpgradePreChecksRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.KubernetesUpgradePreChecksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KubernetesSyncManifests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/management.ManagementService/KubernetesSyncManifests',
            omni_dot_management_dot_management__pb2.KubernetesSyncManifestRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.KubernetesSyncManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSchematic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/CreateSchematic',
            omni_dot_management_dot_management__pb2.CreateSchematicRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.CreateSchematicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSchematicFromRaw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/CreateSchematicFromRaw',
            omni_dot_management_dot_management__pb2.CreateSchematicFromRawRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.CreateSchematicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/management.ManagementService/GetSupportBundle',
            omni_dot_management_dot_management__pb2.GetSupportBundleRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.GetSupportBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadAuditLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/management.ManagementService/ReadAuditLog',
            omni_dot_management_dot_management__pb2.ReadAuditLogRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.ReadAuditLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MaintenanceUpgrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/MaintenanceUpgrade',
            omni_dot_management_dot_management__pb2.MaintenanceUpgradeRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.MaintenanceUpgradeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMachineJoinConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/GetMachineJoinConfig',
            omni_dot_management_dot_management__pb2.GetMachineJoinConfigRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.GetMachineJoinConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateJoinToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/CreateJoinToken',
            omni_dot_management_dot_management__pb2.CreateJoinTokenRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.CreateJoinTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetNodeUniqueToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/ResetNodeUniqueToken',
            omni_dot_management_dot_management__pb2.ResetNodeUniqueTokenRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.ResetNodeUniqueTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/CreateUser',
            omni_dot_management_dot_management__pb2.CreateUserRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/ListUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            omni_dot_management_dot_management__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/UpdateUser',
            omni_dot_management_dot_management__pb2.UpdateUserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/DestroyUser',
            omni_dot_management_dot_management__pb2.DestroyUserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MachinePowerOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/MachinePowerOff',
            omni_dot_management_dot_management__pb2.MachinePowerOffRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.MachinePowerOffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MachinePowerOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/management.ManagementService/MachinePowerOn',
            omni_dot_management_dot_management__pb2.MachinePowerOnRequest.SerializeToString,
            omni_dot_management_dot_management__pb2.MachinePowerOnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
